apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "severus-ai.fullname" . }}
  labels:
    {{- include "severus-ai.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "severus-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "severus-ai.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: severus-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: metrics
              containerPort: 8000

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          env:
            - name: TLS_CERT_PATH
              value: "/etc/tls/tls.crt"
            - name: TLS_KEY_PATH
              value: "/etc/tls/tls.key"
            - name: CA_CERT_PATH
              value: "/etc/tls/ca.crt"
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls"
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "severus-ai.fullname" . }}-tls-secret
