apiVersion: v1
kind: Service
metadata:
  name: {{ include "severus-ai.fullname" . }}
  labels:
    {{- include "severus-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "severus-ai.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8501
    - name: metrics
      port: 8000
      targetPort: 8000
